import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../context/themToggle";
import { Fira_Code, Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import SectionSwitch from "@/components/SectionSwitch";
import AuthProvider from "@/context/authContext";

const InterSans = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const FiraCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  title: "SkillCred",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${FiraCode.className} antialiased flex flex-col items-center justify-start `}
      >
        <SectionSwitch />
        <AuthProvider>
          <ThemeProvider>
            <Navbar />
            <div className=" w-[90%]">{children}</div>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
